export default [
    /* 001 */ { spanish: 'gracias', english: 'thanks' },
    /* 002 */ { spanish: 'ser', english: 'to be', englishComment: ' (somebody)' },
    /* 003 */ { hide: true, spanish: 'a', spanishComment: ' (from Spanish to English)', english: 'to', englishComment: ' (from English to Spanish)' },
    /* 004 */ { spanish: 'ir', english: 'to go' },
    /* 005 */ { spanish: 'estar', english: 'to be', englishComment: ' (location, feeling)' },
    /* 006 */ { spanish: 'bueno', english: 'good' },
    /* 007 */ { hide: true, spanish: 'de', english: 'of' },
    /* 008 */ { hide: true, spanish: 'su', english: ['your', 'her', 'his', 'their'] },
    /* 009 */ { spanish: 'hacer', english: ['to do', 'to make'] },

    /* 010 */ { spanish: 'amigo', english: 'friend' },
    /* 011 */ { spanish: 'por favor', english: 'please' },
    /* 012 */ { hide: true, spanish: 'no', spanishComment: ' (from Spanish to English)', english: 'no', englishComment: ' (from English to Spanish)' },
    /* 013 */ { hide: true, spanish: 'en', english: ['on', 'in'] },
    /* 014 */ { spanish: 'haber', english: 'to have', englishComment: ' (auxiliary, supportive verb)' },
    /* 015 */ { spanish: 'tener', english: ['to have', 'to possess'], englishComment: [' (to possess)', ''] },
    /* 016 */ { hide: true, spanish: ['un', 'uno', 'una'], english: ['a', 'one'] },
    /* 017 */ { spanish: 'ahora', english: 'now' },
    /* 018 */ { hide: true, spanish: 'y', english: 'and' },
    /* 019 */ { new: true, spanish: 'que', english: ['what', 'that'] },

    /* 020 */ { hide: true, spanish: 'por', english: ['for', 'by'] },  // PROBLEM
    /* 021 */ { spanish: 'amar', english: 'to love' },
    /* 022 */ { hide: true, spanish: 'quien', english: 'who' },
    /* 023 */ { hide: true, spanish: 'para', english: ['for', 'to'] },  // 2x PROBLEMs
    /* 024 */ { spanish: 'venir', english: 'to come' },
    /* 025 */ { hide: true, spanish: 'porque', english: 'because' },
    /* 026 */ { hide: true, spanish: ['el', 'la', 'los', 'las'], english: 'the' },
    /* 027 */ { spanish: 'antes', english: 'before' },
    /* 028 */ { spanish: 'mas', english: 'more' },
    /* 029 */ { spanish: 'bien', english: 'well' },

    /* 030 */ { new: true, spanish: ['aqui', 'alli'], english: ['here', 'there'] },
    /* 031 */ { spanish: 'querer', english: 'to want' },
    /* 032 */ { hide: true, spanish: 'hola', english: 'hello' },
    /* 033 */ { hide: true, spanish: 'tu', english: 'you', englishComment: ' (singular)' },
    /* 034 */ { spanish: 'poder', english: 'to be able' },
    /* 035 */ { spanish: 'gustar', english: ['to be pleasing', 'to like'] },
    /* 036 */ { spanish: 'poner', english: 'to put' },
    /* 037 */ { spanish: 'casi', english: 'almost' },
    /* 038 */ { spanish: 'saber', english: 'to know', englishComment: ' (fact or skill)' },
    /* 039 */ { hide: true, spanish: 'como', english: ['like', 'as'] },

    /* 040 */ { hide: true, spanish: 'donde', english: 'where' },
    /* 041 */ { spanish: 'dar', english: 'to give' },
    /* 042 */ { hide: true, spanish: 'pero', english: 'but' },
    /* 043 */ { hide: true, spanish: 'se', english: ['itself', 'herself', 'himself', 'themselves'] },
    /* 044 */ { hide: true, spanish: 'mucho', english: 'much' },
    /* 045 */ { hide: true, spanish: 'nuevo', english: 'new' },
    /* 046 */ { new: true, spanish: 'cuando', english: 'when' },
    /* 047a*/ { hide: true, spanish: 'chico', english: 'boy' },
    /* 047b*/ { hide: true, spanish: 'chica', english: 'girl' },
    /* 048 */ { spanish: 'entender', english: 'to understand' },
    /* 049 */ { hide: true, spanish: 'si', english: ['if', 'yes'] },

    /* 050 */ { hide: true, spanish: 'o', english: 'or' },
    /* 051 */ { spanish: 'feliz', english: 'happy' },
    /* 052 */ { spanish: 'todo', english: ['all', 'every'] },
    /* 053 */ { spanish: 'mismo', english: 'same' },
    /* 054 */ { spanish: 'muy', english: 'very' },
    /* 055 */ { spanish: 'nunca', english: 'never' },
    /* 056 */ { hide: true, spanish: 'yo', english: 'I' },
    /* 057 */ // coded in 049:si -> yes
    /* 058a*/ { hide: true, spanish: 'grande', english: 'big' },
    /* 058b*/ { hide: true, spanish: 'gran', english: 'great' },
    /* 059 */ { new: true, spanish: 'deber', english: ['to owe', 'should'] },

    /* 060 */ { hide: true, spanish: 'usted', english: 'you', englishComment: ' (plural)' },
    /* 061 */ { hide: true, spanish: 'bajo', english: ['low', 'under'] },
    /* 062 */ { hide: true, spanish: 'otro', english: 'other' },
    /* 063 */ { spanish: 'salir', english: 'to leave' },
    /* 064 */ { hide: true, spanish: 'hora', english: 'hour' },
    /* 065 */ { hide: true, spanish: 'desde', english: 'from' },
    /* 066 */ { spanish: 'ver', english: 'to see' },
    /* 067 */ { hide: true, spanish: ['malo', 'mal'], english: 'bad' },
    /* 068 */ { spanish: 'pensar', english: 'to think' },
    /* 069 */ { hide: true, spanish: 'hasta', english: 'until' },

    /* 070 */ // { hide: true, spanish: ['tanto', 'tan'], english: '?', englishComment: ' (used in making comparison' },
    /* 071 */ { hide: true, spanish: 'entre', english: ['between', 'among'] },
    /* 072 */ { hide: true, spanish: 'durante', english: 'during' },
    /* 073 */ { spanish: 'llevar', english: ['to wear', 'to carry'] },
    /* 074 */ { hide: true, spanish: 'siempre', english: 'always' },
    /* 075 */ { spanish: 'empezar', english: 'to begin' },
    /* 076a*/ { hide: true, spanish: 'el', english: 'he' },
    /* 076b*/ { hide: true, spanish: 'ella', english: 'she' },
    /* 076c*/ { hide: true, spanish: ['ellos', 'ellas'], english: 'they' },
    /* 077 */ { spanish: 'leer', english: 'to read' },
    /* 078 */ { spanish: 'cosa', english: 'thing' },
    /* 079 */ { spanish: 'sacar', english: ['to take out', 'to remove'] },

    /* 080 */ { spanish: 'conocer', english: 'to know', englishComment: ' (person or place)' },
    /* 081 */ { hide: true, spanish: 'primero', english: 'first' },
    /* 082 */ { new: true, spanish: 'andar', english: 'to walk', englishComment: ' (when enjoying...)' },
    /* 083 */ { hide: true, spanish: 'sobre', english: ['over', 'about'] },
    /* 084 */ { spanish: 'echar', english: 'to throw' },
    /* 085 */ { new: true, spanish: 'sin', english: 'without' },
    /* 086 */ { spanish: 'decir', english: 'to say' },
    /* 087 */ { spanish: 'trabajar', english: 'to work' },
    /* 088 */ { hide: true, spanish: 'nosotros', english: 'we' },
    /* 089 */ { hide: true, spanish: 'tambien', english: 'also' },

    /* 090 */ { hide: true, spanish: 'adios', english: 'goodbye' },
    /* 091 */ { spanish: 'comer', english: 'to eat' },
    /* 092 */ { spanish: 'triste', english: 'sad' },
    /* 093 */ { spanish: 'pais', english: 'country' },
    /* 094 */ { spanish: 'escuchar', english: 'to listen' },
    /* 095 */ { spanish: 'hombre', english: 'man' },
    /* 096 */ { spanish: 'mujer', english: 'woman' },
    /* 097 */ // le
    /* 098 */ { spanish: 'creer', english: ['to believe', 'to think'] },
    /* 099 */ { spanish: 'encontrar', english: 'to find' },

    /* 100 */ { spanish: 'beber', english: 'to drink' },

    { spanish: 'mirar', english: 'to look' },
    { spanish: 'hablar', english: 'to talk' },
    { spanish: 'sentir', english: 'to feel' },
    { spanish: 'oir', english: 'to hear' },
    { spanish: 'rapido', english: 'fast' },
    { spanish: 'lento', english: 'slow' },
    { spanish: 'tuerte', english: 'strong', englishComment: ' (when speaking)' },
    { spanish: 'suave', english: 'soft' },
    { spanish: 'caro', english: 'car' },

    { new: true, spanish: 'caminar', english: 'to walk', englishComment: ' (to some location)' },
    { new: true, spanish: 'guineo', english: 'banana' },
    { new: true, spanish: 'respuesta', english: 'answer' },
    { new: true, spanish: 'esta', english: 'this', englishComment: ' (if you can touch it)' },
    { new: true, spanish: 'esa', english: 'this', englishComment: ' (if you can\'t touch it' },
    { new: true, spanish: 'con', english: 'with' },
    { new: true, spanish: 'salud', english: 'health' },
    { new: true, spanish: 'perfecta', english: 'perfect' },
];
